import { describe, it, expect } from 'vitest';
import { parseTelemetryPayload, parseDeviceStatus } from './parser';
import {
  getTelemetryTopic,
  getStatusTopic,
  extractDeviceIdFromTopic,
  isTelemetryTopic,
  isStatusTopic,
} from './topics';

describe('Telemetry Parser (PRD Section 7, 8, 17)', () => {
  const validPayload = JSON.stringify({
    device_id: 'esp32s3-ABCD12345678',
    sequence: 42,
    timestamp: 1790041200,
    uptime_s: 381,
    temperature_c: 28.43,
    humidity_percent: 71.20,
    mq135_raw: 1852,
    mq135_adc_mv: 1478,
    mq135_sensor_mv: 2463.33,
    wifi_rssi_dbm: -54,
  });

  it('successfully parses and validates the exact PRD telemetry payload', () => {
    const result = parseTelemetryPayload(validPayload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.device_id).toBe('esp32s3-ABCD12345678');
      expect(result.data.sequence).toBe(42);
      expect(result.data.temperature_c).toBe(28.43);
      expect(result.data.humidity_percent).toBe(71.2);
      expect(result.data.mq135_raw).toBe(1852);
      expect(result.data.mq135_adc_mv).toBe(1478);
      expect(result.data.mq135_sensor_mv).toBe(2463.33);
      expect(result.data.wifi_rssi_dbm).toBe(-54);
    }
  });

  it('successfully parses real-world ESP32 payload with high/saturated MQ135 sensor voltage', () => {
    const realHardwarePayload = JSON.stringify({
      device_id: 'esp32s3-E8A851858428',
      sequence: 17,
      timestamp: 1789997827,
      uptime_s: 85,
      temperature_c: 32.80,
      humidity_percent: 62.60,
      mq135_raw: 4095,
      mq135_adc_mv: 3134,
      mq135_sensor_mv: 5223.33,
      wifi_rssi_dbm: -71,
    });

    const result = parseTelemetryPayload(realHardwarePayload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.device_id).toBe('esp32s3-E8A851858428');
      expect(result.data.sequence).toBe(17);
      expect(result.data.temperature_c).toBe(32.8);
      expect(result.data.humidity_percent).toBe(62.6);
      expect(result.data.mq135_raw).toBe(4095);
      expect(result.data.mq135_adc_mv).toBe(3134);
      expect(result.data.mq135_sensor_mv).toBe(5223.33);
      expect(result.data.wifi_rssi_dbm).toBe(-71);
    }
  });

  it('handles malformed JSON syntax gracefully without throwing (PRD Section 17)', () => {
    const malformed = '{ "device_id": "esp32s3", "sequence": 42, broken';
    const result = parseTelemetryPayload(malformed);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('Malformed JSON');
    }
  });

  it('rejects empty or non-object payloads', () => {
    expect(parseTelemetryPayload('').success).toBe(false);
    expect(parseTelemetryPayload('null').success).toBe(false);
    expect(parseTelemetryPayload('12345').success).toBe(false);
    expect(parseTelemetryPayload('["an", "array"]').success).toBe(false);
  });

  it('rejects payloads with missing required telemetry fields', () => {
    const missingTemp = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 1,
      timestamp: 1790041200,
      uptime_s: 10,
      // temperature_c missing
      humidity_percent: 50,
      mq135_raw: 1000,
      mq135_adc_mv: 1000,
      mq135_sensor_mv: 1500,
      wifi_rssi_dbm: -60,
    });
    const result = parseTelemetryPayload(missingTemp);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('temperature_c');
    }
  });

  it('rejects out-of-range sensor readings', () => {
    const invalidHumid = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 1,
      timestamp: 1790041200,
      uptime_s: 10,
      temperature_c: 25.0,
      humidity_percent: 150.0, // > 100% is physically impossible
      mq135_raw: 1000,
      mq135_adc_mv: 1000,
      mq135_sensor_mv: 1500,
      wifi_rssi_dbm: -60,
    });
    const result = parseTelemetryPayload(invalidHumid);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('humidity_percent');
    }
  });

  it('rejects device ID mismatch when expectedDeviceId is specified', () => {
    const result = parseTelemetryPayload(validPayload, 'esp32s3-OTHERDEVICE');
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('Device ID mismatch');
    }
  });

  it('accepts zero timestamp from unsynced ESP32 NTP and gracefully falls back to valid client timestamp', () => {
    const unsyncedNtpPayload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 1,
      timestamp: 0, // Generated by SmartCIty-ESP32.ino when now < 1700000000
      uptime_s: 15,
      temperature_c: 28.5,
      humidity_percent: 70.0,
      mq135_raw: 1800,
      mq135_adc_mv: 1400,
      mq135_sensor_mv: 2333.33,
      wifi_rssi_dbm: -50,
    });
    const result = parseTelemetryPayload(unsyncedNtpPayload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.timestamp).toBeGreaterThan(1700000000);
      expect(result.data.temperature_c).toBe(28.5);
      expect(result.data.humidity_percent).toBe(70.0);
    }
  });

  it('successfully parses rain sensor metrics when present in payload', () => {
    const rainPayload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 55,
      timestamp: 1790041200,
      uptime_s: 410,
      temperature_c: 26.2,
      humidity_percent: 85.4,
      mq135_raw: 1400,
      mq135_adc_mv: 1120,
      mq135_sensor_mv: 1866.67,
      rain_raw: 1250,
      rain_status: 'Hujan Lebat',
      is_raining: true,
      wifi_rssi_dbm: -58,
    });
    const result = parseTelemetryPayload(rainPayload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.rain_raw).toBe(1250);
      expect(result.data.rain_status).toBe('Hujan Lebat');
      expect(result.data.is_raining).toBe(true);
    }
  });

  it('rejects invalid rain_raw out of 12-bit ADC range', () => {
    const invalidRainPayload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 56,
      timestamp: 1790041200,
      uptime_s: 415,
      temperature_c: 26.2,
      humidity_percent: 85.4,
      mq135_raw: 1400,
      mq135_adc_mv: 1120,
      mq135_sensor_mv: 1866.67,
      rain_raw: 5000, // Invalid: > 4095
      wifi_rssi_dbm: -58,
    });
    const result = parseTelemetryPayload(invalidRainPayload);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('rain_raw');
    }
  });

  it('successfully parses water level sensor metrics when present in payload', () => {
    const waterPayload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 60,
      timestamp: 1790041200,
      uptime_s: 430,
      temperature_c: 27.1,
      humidity_percent: 82.0,
      mq135_raw: 1500,
      mq135_adc_mv: 1200,
      mq135_sensor_mv: 2000,
      water_level_raw: 2850,
      water_level_cm: 3.1,
      flood_status: 'Siaga',
      is_flood_warning: true,
      wifi_rssi_dbm: -60,
    });
    const result = parseTelemetryPayload(waterPayload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.water_level_raw).toBe(2850);
      expect(result.data.water_level_cm).toBe(3.1);
      expect(result.data.flood_status).toBe('Siaga');
      expect(result.data.is_flood_warning).toBe(true);
    }
  });

  it('rejects invalid water_level_raw > 4095', () => {
    const invalidWaterPayload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 61,
      timestamp: 1790041200,
      uptime_s: 435,
      temperature_c: 27.1,
      humidity_percent: 82.0,
      mq135_raw: 1500,
      mq135_adc_mv: 1200,
      mq135_sensor_mv: 2000,
      water_level_raw: 5000,
      wifi_rssi_dbm: -60,
    });
    const result = parseTelemetryPayload(invalidWaterPayload);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('water_level_raw');
    }
  });

  it('successfully parses ultrasonic flood sensor metrics (water_distance_cm & water_level_cm)', () => {
    const ultrasonicPayload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 62,
      timestamp: 1790041200,
      uptime_s: 440,
      temperature_c: 27.5,
      humidity_percent: 78.0,
      mq135_raw: 1450,
      mq135_adc_mv: 1150,
      mq135_sensor_mv: 1950,
      water_distance_cm: 8.5,
      water_level_cm: 21.5,
      flood_status: 'Siaga',
      is_flood_warning: true,
      wifi_rssi_dbm: -58,
    });
    const result = parseTelemetryPayload(ultrasonicPayload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.water_distance_cm).toBe(8.5);
      expect(result.data.water_level_cm).toBe(21.5);
      expect(result.data.flood_status).toBe('Siaga');
      expect(result.data.is_flood_warning).toBe(true);
    }
  });

  it('rejects invalid water_distance_cm out of physical range', () => {
    const invalidDistPayload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 63,
      timestamp: 1790041200,
      uptime_s: 445,
      temperature_c: 27.5,
      humidity_percent: 78.0,
      mq135_raw: 1450,
      mq135_adc_mv: 1150,
      mq135_sensor_mv: 1950,
      water_distance_cm: 999, // > 500
      wifi_rssi_dbm: -58,
    });
    const result = parseTelemetryPayload(invalidDistPayload);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain('water_distance_cm');
    }
  });

  it('correctly parses optional air_quality_status and is_gas_polluted fields', () => {
    const payload = JSON.stringify({
      device_id: 'esp32s3-ABCD12345678',
      sequence: 64,
      timestamp: 1790041200,
      uptime_s: 450,
      temperature_c: 28.0,
      humidity_percent: 70.0,
      mq135_raw: 3200,
      mq135_adc_mv: 2450,
      mq135_sensor_mv: 4083.33,
      air_quality_status: 'Tercemar',
      is_gas_polluted: true,
      wifi_rssi_dbm: -58,
    });
    const result = parseTelemetryPayload(payload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.air_quality_status).toBe('Tercemar');
      expect(result.data.is_gas_polluted).toBe(true);
    }
  });
});

describe('Device Status Parser (PRD Section 14)', () => {
  it('correctly parses "online" and "offline" status payloads', () => {
    expect(parseDeviceStatus('online')).toBe('online');
    expect(parseDeviceStatus('  ONLINE  ')).toBe('online');
    expect(parseDeviceStatus('offline')).toBe('offline');
    expect(parseDeviceStatus('  Offline ')).toBe('offline');
  });

  it('safely handles unexpected status payloads as unknown', () => {
    expect(parseDeviceStatus('')).toBe('unknown');
    expect(parseDeviceStatus('rebooting')).toBe('unknown');
    expect(parseDeviceStatus('error')).toBe('unknown');
  });
});

describe('MQTT Topic Utilities (PRD Section 5)', () => {
  it('generates proper namespace topics', () => {
    expect(getTelemetryTopic('esp32s3-01')).toBe('aethersense/esp32s3-01/telemetry');
    expect(getStatusTopic('esp32s3-01')).toBe('aethersense/esp32s3-01/status');
  });

  it('extracts device ID and validates topic patterns', () => {
    const topic = 'aethersense/esp32s3-ABCD12345678/telemetry';
    expect(extractDeviceIdFromTopic(topic)).toBe('esp32s3-ABCD12345678');
    expect(isTelemetryTopic(topic)).toBe(true);
    expect(isStatusTopic(topic)).toBe(false);

    const statusTopic = 'aethersense/esp32s3-ABCD12345678/status';
    expect(isStatusTopic(statusTopic)).toBe(true);
    expect(isTelemetryTopic(statusTopic)).toBe(false);
  });
});
